Fixed a bunch of bugs
bastionzero/zli pull request #121
Opened 2021-06-17 16:55 UTC by Nabeelperson

## Description of the change

Handle http errors more gracefully
Fix copy paste regression
Add close connection --all flag, that generates a new cli-space
Fixed npm installs ssh-proxy-config output

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (code change with no functionality change)
- [x] Enhancement (minor change below the level of a feature)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Remove feature (removes a feature we don't support anymore)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related JIRA tickets

Relates to JIRA:
https://commonwealthcrypto.atlassian.net/browse/CWC-772
https://commonwealthcrypto.atlassian.net/browse/CWC-773
https://commonwealthcrypto.atlassian.net/browse/CWC-859
https://commonwealthcrypto.atlassian.net/browse/CWC-860

## Relevant release note information

Release Notes:

## Potential Security Impacts

Does this PR have any security impact?
Does it fix a security issue?
Does it add attack surface?
Why do we think this change is safe?

## Checklists

### Development

- [ ] Does the code changed/added as part of this pull request have test coverage?
- [ ] Do all tests related to the changed code pass in development?
- [ ] Have you ensured that at least one other person has tested your code?
- [ ] Have you tested the code?
- [ ] Have you attached any pictures (if relevant)?

2021-06-17 18:52 UTC, lipmas commented on src/http.service/http.service.ts
> +        errorMessage = JSON.parse(error.response.body as string).errorMsg.errorMessage;
The response body will only have a json object containing `errorType` and `errorMsg` if this is a custom `IApplicationException` that is mapped by the `ExceptionHandlerMiddleware`. So this code is going to throw an unhandled exception now in case of 401 or 502 errors.

2021-06-17 18:52 UTC, lipmas commented on src/cli-driver.ts
> +                    if(processName.includes('node')) processName = 'zli';
Does this also apply to devs that package and run the zli with `npm run package` and `./bin/zli-macos`?

Also what is the process name when running zli from an installed npm package and why does not using the full path work?

2021-06-17 20:08 UTC, Nabeelperson commented on src/cli-driver.ts
> +                    if(processName.includes('node')) processName = 'zli';
That should be fine, as those are statically compiled.

2021-06-17 20:08 UTC, Nabeelperson commented on src/cli-driver.ts
> +                    if(processName.includes('node')) processName = 'zli';
From an NPM package installation, the process name is actually `node`. There is no full path as NPM installation actually pulls source code and runs it locally.

2021-06-17 20:25 UTC, Nabeelperson commented on src/http.service/http.service.ts
> +        errorMessage = JSON.parse(error.response.body as string).errorMsg.errorMessage;
https://github.com/bastionzero/zli/pull/121/commits/494ac889b837a8d44c9f95f031cf47e7e9f23e27

2021-06-17 20:42 UTC, ymarcus93 requested changes

2021-06-17 20:42 UTC, ymarcus93 commented on src/handlers/connect.handler.ts
> +    let cliSpaceId = (await getCliSpace(sessionService, logger)).id;
Move `.id` call bellow so that the `zli` won't error when the cli space does not exist

2021-06-17 20:46 UTC, Nabeelperson commented on src/handlers/connect.handler.ts
> +    let cliSpaceId = (await getCliSpace(sessionService, logger)).id;
8df52f0

2021-06-17 20:51 UTC, ymarcus93 approved these changes
>  Fix copy paste regression

Tested. Looks good!

2021-06-18 21:27 UTC, lipmas commented on src/http.service/http.service.ts
> +        errorMessage = JSON.parse(error.response.body as string).errorMsg.errorMessage;
`JSON.parse` i think will throw an exception if the response body is just text instead of json which it might be for non-custom errors.

2021-06-21 17:31 UTC, lipmas commented on src/handlers/middleware.handler.ts
> +            logger.debug(`Failed to fetch dynamic access configs: ${e}`);
nit: why not make these error level?

2021-06-21 17:31 UTC, lipmas commented on src/http.service/http.service.ts
> +            this.logger.error(`Server Error:\n${errorMessage}`);
this shows up as:
```
[Error][2021-06-21 13:25:57] Server Error:
[object Object]
```

unless you convert it to a string with [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). Before i was using `JSON.stringify(errorMessage, null, 2)` so that it prints the json object with space indentation for easier readability.

2021-06-21 18:39 UTC, Nabeelperson commented on src/http.service/http.service.ts
> +            this.logger.error(`Server Error:\n${errorMessage}`);
f6e44bc

2021-06-21 18:40 UTC, Nabeelperson commented on src/handlers/middleware.handler.ts
> +            logger.debug(`Failed to fetch dynamic access configs: ${e}`);
f6e44bc

2021-06-21 18:43 UTC, lipmas approved these changes
LGTM

2021-06-21 18:47 UTC, merged