Datachannel Parallelization
bastionzero/zli pull request #234
Opened 2021-10-20 14:40 UTC by lgmugnier

## Description of the change

We need to decouple the datachannel from the websocket so that both can be scaled up/down independently of each other.  It will also make it so that if a websocket breaks, it doesn't immediately destroy the keysplitting session in case the client wants to reconnect.  This requires a major refactor of the current kube agent which includes:

1. [CWC-1170](https://commonwealthcrypto.atlassian.net/browse/CWC-1170) Moving the HTTP Server out of the Kube Daemon plugin and into a higher-level place so that we can add in logic to create, destroy, and manage websockets and datachannels.
2. [CWC-1171](https://commonwealthcrypto.atlassian.net/browse/CWC-1171) We need to do something similar with the Control Channel for the agent so that it has a parallel ability to create, destroy, and manage websockets and datachannels.
3. [CWC-1172](https://commonwealthcrypto.atlassian.net/browse/CWC-1172) Tombs are a better way for us to internally manage go routines so we should include that library in this refactor.
4. [CWC-1173](https://commonwealthcrypto.atlassian.net/browse/CWC-1173) We need to formalize websocket and datachannel creation and destruction so that we can start them up and shut them down (and recover from unexpected closes) without memory leaks and without inconveniencing the user.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (code change with no functionality change)
- [ ] Enhancement (minor change below the level of a feature)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Remove feature (removes a feature we don't support anymore)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related JIRA tickets

Relates to JIRA: CWC-1169, CWC-1170, CWC-1171, CWC-1172, CWC-1173

## Relevant release note information

Release Notes:

## Potential Security Impacts

Does this PR have any security impact?
Does it fix a security issue?
Does it add attack surface?
Why do we think this change is safe?

## Checklists

### Development

- [ ] Does the code changed/added as part of this pull request have test coverage?
- [ ] Do all tests related to the changed code pass in development?
- [ ] Have you ensured that at least one other person has tested your code?
- [ ] Have you tested the code?
- [ ] Have you attached any pictures (if relevant)?

2021-11-08 20:07 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +	websocket.Subscribe("", control) // this is a bit of a hack, but bastion does not currently have the concept of a channel id
So bit confused, currently are we setting it to `""` since there will only be one datachannel and websocket?

2021-11-08 20:15 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +			for ws.ready {
Do we need the double for here?

2021-11-08 20:17 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +					w.shabtis.Kill(rerr) // TODO: implement reconnect flow
important todo that needs to get done before merge, + check against `autoReconnect`

2021-11-08 21:16 UTC, sidpremkumar requested changes

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +			e.logger.Info("stream ended")
maybe exec stream ended so we know what type of stream we are talking about

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +				// Check for agent-initiated end e.g. user typing 'exit'
this is handled inside `processMessage` I believe now

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/restapi/restapi.go
> +	// channels for sending and recieving messages
receiving

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +func NewExecAction(logger *lggr.Logger,
we should keep this consistent with the agent code and call this function `New`

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/stream/stream.go
> +func NewStreamAction(logger *lggr.Logger,
similar this should read `New`

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/actions/restapi/restapi.go
> +func NewRestApiAction(logger *lggr.Logger,
similar this should read `New`

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/utils/utils.go
> -func GetHeaders(headers http.Header) map[string][]string {
This I believe is still used, so dont wanna delete that.

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bctl/daemon/plugin/kube/kube.go
> +	default:
going to need portforward somewhere here

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/agentmessage/agentmessage.go
> +// func New(channelId string, messageType string, messagePayload []byte) AgentMessage {
can we remove this?

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bzerolib/logger/logger.go
>  // TODO: instead of assigning random uuid, the control channel and data channel should both use
Can we remove this TODO now? We still have to use the connection Id, but in terms of the work here this todo might not be relevent anymore.

2021-11-08 21:16 UTC, sidpremkumar commented on kube-go-assets/bzerolib/logger/logger.go
>  // TODO: instead of assigning random uuid, the control channel and data channel should both use
Also there is some code at the bottom of this file that I believe can be removed,

```go
// ??
// func (l *Logger) Fatal(err error) {
// 	l.logger.Fatal().
// 		Msg(err.Error())
// }
```

since we are not using Fatel? Otherwise we can keep it if we think we will use it in the future

2021-11-08 21:53 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +			for ws.ready {
yup. the idea is that the first for is to loop infinitely and the second for is to loop finitely only when the websocket is ready otherwise, it will stop listening to the channels and only start up again when the websocket is ready.  At least that's what I was going for, maybe I was wrong.

2021-11-10 16:58 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
> +	config, _ := vault.LoadVault()
this is addressed in my other PR for reg-debuggability https://github.com/bastionzero/zli/pull/229

2021-11-10 16:58 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
> +		// Why do we need these?  Can we remove them?
let's do a full walk through of these at a later date

2021-11-10 17:00 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
> +	wsLogger := logger.GetWebsocketLogger(wsId) // TODO: replace with actual connectionId
yes.  This ConnectionId should be provided by the bastion when it connects I think.  This is an issue with the ordering the logger in that I do it before the websocket even reaches out to Bastion, so the logger will be inaccurate.

2021-11-10 17:06 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +	websocket.Subscribe("", control) // this is a bit of a hack, but bastion does not currently have the concept of a channel id
Yes.  The ChannelId is mostly for distinguishing multiple channels over a single websocket but the control channel has its own dedicated websocket.  This also makes it so there can only ever be one control channel associated with a given websocket at any time.  Updated comments on this line to reflect this.

2021-11-10 18:32 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +					w.shabtis.Kill(rerr) // TODO: implement reconnect flow
This was a comment for the reconnect flow that would only be possible for connection service.  Aka if bastion/agent connection breaks, we can use the reconnect flow but in the future we're probably going to want a formal message maybe

2021-11-10 18:40 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		for {
maybe? I think it's fine for now but once we integrate with connection service and have a better reconnect flow, then for sure

2021-11-10 19:47 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/utils/utils.go
> -func GetHeaders(headers http.Header) map[string][]string {
it's still there

2021-11-10 19:47 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/agentmessage/agentmessage.go
> +// func New(channelId string, messageType string, messagePayload []byte) AgentMessage {
waiting to remove this

2021-11-11 14:01 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +				// parentDoneChan <- tmb.Err().Error() // report death reason to parent
yes but we have nothing to do with it right now.  Maybe later when we have a better control channel.  Printing it to logs for now

2021-11-11 14:05 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/stream/stream.go
> +					s.logger.Info("Received EOF on stream")
Ah yeah I was thinking that it's the stream action but you are correct, this just makes it super generic.  Since it could also be a Follow stream and this could become confusing, could I change it to "Received EOF on Stream action stream?" or something (open to alts)

2021-11-11 14:17 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
> +	// profiling code
Nope we don't 698faa3

2021-11-11 14:17 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +// const (
698faa3

2021-11-11 14:17 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +	websocket.Subscribe("", control) // this is a bit of a hack, but bastion does not currently have the concept of a channel id
698faa3

2021-11-11 14:17 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +			for ws.ready {
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +	tmb       tomb.Tomb
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +	// register with websocket so datachannel can send a recieve messages
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +				// parentDoneChan <- tmb.Err().Error() // report death reason to parent
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +			if err := d.startPlugin(PluginName(x[0])); err != nil {
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/kube.go
>  	x := strings.Split(action, "/")
698faa3

2021-11-11 14:18 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +				datachannel.tmb.Kill(errors.New("daemon killed the radio star"))
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +			e.logger.Info("stream ended")
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/restapi/restapi.go
> +	// channels for sending and recieving messages
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +func NewExecAction(logger *lggr.Logger,
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/stream/stream.go
> +func NewStreamAction(logger *lggr.Logger,
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/restapi/restapi.go
> +func NewRestApiAction(logger *lggr.Logger,
698faa3

2021-11-11 14:19 UTC, lgmugnier commented on kube-go-assets/bzerolib/logger/logger.go
>  // TODO: instead of assigning random uuid, the control channel and data channel should both use
698faa3

2021-11-11 14:20 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/kube.go
> +	default:
d1d03af

2021-11-11 14:20 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/utils/utils.go
> -func GetHeaders(headers http.Header) map[string][]string {
d1d03af

2021-11-11 14:23 UTC, lgmugnier commented on kube-go-assets/bctl/agent/datachannel/datachannel.go
> +				// parentDoneChan <- tmb.Err().Error() // report death reason to parent
yes but we have nothing to do with it right now. Maybe later when we have a better control channel. Printing it to logs for now

2021-11-11 14:37 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +				// Check for agent-initiated end e.g. user typing 'exit'
sorry must have rebased wrong

2021-11-11 14:42 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/exec/exec.go
> +	if requestId != e.requestId {
8c487fd

2021-11-11 14:42 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/stream/stream.go
> +		if streamActionRequest.RequestId != s.requestId {
8c487fd

2021-11-11 14:42 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/stream/stream.go
> +					s.logger.Info("Received EOF on stream")
8c487fd

2021-11-11 14:42 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go
> +				// Check for agent-initiated end e.g. user typing 'exit'
8c487fd

2021-11-11 16:37 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/agent.go
> +		// Why do we need these?  Can we remove them?
for now I believe its possible to remove environment_id, so if we can we should do that now and remove this comment since we do know we need them.

2021-11-11 16:54 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/agentmessage/agentmessage.go
> +// func New(channelId string, messageType string, messagePayload []byte) AgentMessage {
? not sure I follow

2021-11-11 16:57 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		ticker := time.NewTicker(10 * time.Millisecond)
Can we extract this function (or at least `10 * time.Millisecoond`) to a common util, we also share the same logic in `datachannel.go`

2021-11-11 16:58 UTC, sidpremkumar commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +			for ws.ready {
no that makes sense, so I assume then `for ws.ready {}` if `ws.ready` was false we would block there correct?

2021-11-11 22:09 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +			for ws.ready {
yes, exactly

2021-11-11 22:11 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/agentmessage/agentmessage.go
> +// func New(channelId string, messageType string, messagePayload []byte) AgentMessage {
Technically this is the right way to do this.  I want the agentmessage package to be in control of inserting its own `SchemaVersion` so none of the other packages needs to think about it.  rn I have it as the default json value, but I think that if we want to make this more "pro", we have to use this function.  But I'm a coward and am holding out until the last second in case there's another option

2021-11-11 22:13 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		ticker := time.NewTicker(10 * time.Millisecond)
I think since it's only in those two places for now, it's better just to keep it transparent and not obscure it.  It might change too when we integrate with the connection service, so it's probably not worth putting the effort in now.

2021-11-17 20:21 UTC, ymarcus93 requested changes
I like the refactors done in this PR. I like the separation between DCs+CCs and websockets which is nice.

**Open, general questions**:

1) Does this PR have it so CC is on its own separate websocket, and DCs are all managed on a single, separate websocket (by using `ChannelId` to let `websocket.go` distinguish which DC to send the incoming message to). That is, are there two websockets in total? Or is there still 1 websocket per DC with the option of allowing more than one DC to exist on a single WS if we want for certain plugins?
2) How have we tested that everything is working as before? Have we tested all actions and use-cases manually? Let me know if I should run some manual tests myself on this branch.

Also, haven't confirmed yet because a lot has been refactored, but I think my comment here: https://github.com/bastionzero/zli/pull/207#discussion_r715700978 has been addressed. I don't think we're handling each incoming message on the WS/DC on its own goroutine anymore, so we've now prevented some of the data races explained in that comment.

To elaborate,

https://github.com/bastionzero/zli/blob/0bb94f06132154dfc04992ff15df1f9e4d4cb0ff/kube-go-assets/bctl/daemon/plugin/kube/actions/exec/exec.go#L110-L121

unless there is some strange reordering going on in the SignalR Hub (have not confirmed), I'm not sure we need `streamQueue` anymore in the code block above (and any variants of it in other actions--e.g. perhaps `port.go`?). Don't remove `streamQueue` in this PR, but we should write a ticket to investigate if it is needed anymore. CC @sidpremkumar 

----
Comments that may apply to other parts of the codebase:
- `doneChan` usage. Do plugins/actions need `doneChan` if `tomb` is being used?
- Use `tomb.Go` so that `tomb` can track the goroutines and `Wait` can wait for tracked goroutines to terminate.
- Any pattern where we have a `for` loop constantly checking for a conditon to be true, even if done in a separate goroutine, should use either a channel or `sync.Cond` to be signaled when there is work to do (because the condition has changed). Good article on `sync.Cond`: https://lukechampine.com/cond.html

2021-11-18 21:24 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/datachannel/datachannel.go
> +	lastMessage plugin.ActionWrapper
You're correct.  If we get an error on a keysplitting message, then we use these to make sure we're not dropping any messages.

2021-11-18 21:24 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +				websocket.Client.Close(errors.New("websocket closed on daemon"))
71168ef

2021-11-18 21:24 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
>  type ControlChannel struct {
71168ef

2021-11-18 21:29 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		}
I think you're right.  I thought I had put this in here for a good reason, but I can't think of it

2021-11-18 21:29 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +	w.tmb.Wait()
71168ef

2021-11-18 21:29 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +				case <-ws.tmb.Dying():
71168ef

2021-11-18 21:52 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
> +		// Why do we need these?  Can we remove them?
86d2676

2021-11-18 22:02 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +	ready      bool
> Does this PR have it so CC is on its own separate websocket, and DCs are all managed on a single, separate websocket (by using ChannelId to let websocket.go distinguish which DC to send the incoming message to). That is, are there two websockets in total? Or is there still 1 websocket per DC with the option of allowing more than one DC to exist on a single WS if we want for certain plugins?

Yes.  For right now we only have 2 websockets: one for the control channel (bastion <-> agent) and another for all of our datachannels (daemon <-> agent). In the future, once we've integrated with the connection service, we'll have the freedom to scale the websockets more.

> How have we tested that everything is working as before? Have we tested all actions and use-cases manually? Let me know if I should run some manual tests myself on this branch.

We are testing this manually right now, feel free to test yourself.

> unless there is some strange reordering going on in the SignalR Hub (have not confirmed), I'm not sure we need streamQueue anymore in the code block above (and any variants of it in other actions--e.g. perhaps port.go?). Don't remove streamQueue in this PR, but we should write a ticket to investigate if it is needed anymore.

I think we should keep this in for now just because I feel like there's always a risk of things being out of order and it's always better to be safe than sorry because we do have two websockets instead of one.

> Comments that may apply to other parts of the codebase:
> 
> doneChan usage. Do plugins/actions need doneChan if tomb is being used?

It's essentially being used as a local tomb and a way for these local tombs to close each other without having to kill the big daddy tomb.  I understand your point but I didn't think it really needed changing, feel free to let me know if you disagree.

> Use tomb.Go so that tomb can track the goroutines and Wait can wait for tracked goroutines to terminate.

Yup, figured this one out recently and it's been committed.

> Any pattern where we have a for loop constantly checking for a conditon to be true, even if done in a separate goroutine, should use either a channel or sync.Cond to be signaled when there is work to do (because the condition has changed). Good article on sync.Cond: https://lukechampine.com/cond.html

I think `sync.Cond` is a great idea.

> Is it fine to set it to true only in case (1)? Is it safe to assume ReadyBastionToClient is the first message the Bastion sends to the other party when the connection is ready? Or is ready supposed to indicate that the websocket connection is established (i.e. Connect returns successfully)?

In regards to below, the websocket is doing a little heavy lifting here because it's handling cases for both the daemon and the agent which do this ready dance differently.  So, for right now, it will have to stay like this to avoid unnecessary complexity in the bastion.

> Shouldn't it be retrying using exponential backoff if some error occurs in Connect? There was a PR by @sidpremkumar which added this somewhere using some standard backoff library. Will this be added here?

Sid did make a comment about this [above](https://github.com/bastionzero/zli/pull/234#discussion_r745067507), we haven't done it yet but you're correct.

> Also, haven't confirmed yet because a lot has been refactored, but I think my comment here: #207 (comment) has been addressed. I don't think we're handling each incoming message on the WS/DC on its own goroutine anymore, so we've now prevented some of the data races explained in that comment.

Actually, we still need some async-ness here because of how keysplitting works vs. streams but I've addressed your issues by pushing keysplitting to a queue which gets processed in series while still allowing the datachannel to receive streams.

2021-11-18 22:15 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +						channel.Receive(agentMessage)
But the websocket is not in charge of creating and destroying the datachannels, that's the responsibility of the httpserver and the control channel.  So we have a different pubsub setup than in the blog post.  One entity creates and manages, while the datachannel is responsible for subbing and unsubbing.  

> we can use a select statement on publishing a message to a channel and adding a <-ws.tmb.Dying(): so that websocket.go does not block on sending a channel if the tmb has been told to die.

I might be wrong but because we don't technically close any of the channels, websocket would never block on this, the message would just be put into a channel and never processed and eventually would be garbage collected.

Also I absolutely think the client should be the one setting the buffer size since it's the client that knows what size buffer it should have based on its own use case.

2021-11-19 15:32 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/stream/stream.go
> +	doneChan         chan bool
These `doneChan`s are used as essentially local tombs.  I see you're point (they could be tombs) I just didn't think it was all that important but that's maybe something we'll think is important later

2021-11-19 16:58 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		time.Sleep(time.Second * sleepIntervalInSeconds)
b23a82e

2021-11-19 16:59 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		ticker := time.NewTicker(10 * time.Millisecond)
Removed b23a82e

2021-11-19 17:00 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +		}
b23a82e

2021-11-19 17:00 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +	return len(w.channels)
b23a82e

2021-11-19 17:00 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
>  func (w *Websocket) Receive() error {
b23a82e

2021-11-19 19:22 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/httpserver/httpserver.go
> +
b23a82e

2021-11-19 19:28 UTC, lgmugnier commented on kube-go-assets/bctl/agent/agent.go
>  }
> Also, listening for SIGINT should also be done in daemon.go. Right now, I think we do kill -9 in zli disconnect. But instead if we changed it to kill -SIGTERM we could also give the chance for the daemon to gracefully clean up.

> Oh also, we should give daemon a grace period to clean up similar to how Kube gives a grace period before killing the agent.

Good idea but out of scope for this PR, could you write a ticket for this please @ymarcus93

2021-11-19 20:52 UTC, ymarcus93 commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +	ready      bool
> I think sync.Cond is a great idea but I also think that it's not the easiest to understand on first glance. I understand the benefit, but until we start doing some heavy optimization I think this way makes it easier to understand which I think should be a higher priority atm. Although I did add a comment to remind us if/when the time comes in 450aec4

Fair point. If we don't want to use `sync.Cond` we could also use a channel that we just `close` to signal readiness. But the problem with this is you can only close a channel once. That's why I was asking in a different thread if we could simplify how many times `ready` flips on and off.

But given the following:

> In regards to below, the websocket is doing a little heavy lifting here because it's handling cases for both the daemon and the agent which do this ready dance differently. So, for right now, it will have to stay like this to avoid unnecessary complexity in the bastion.

It seems we can't use a channel unless we split `ready` into two different things for agent vs daemon so we can just `close` once per. We can revisit `sync.Cond` at a later point.

2021-11-19 21:00 UTC, ymarcus93 commented on kube-go-assets/bctl/agent/agent.go
>  }
Done. See: CWC-1319

2021-11-19 21:20 UTC, ymarcus93 commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +						channel.Receive(agentMessage)
> But the websocket is not in charge of creating and destroying the datachannels, that's the responsibility of the httpserver and the control channel. So we have a different pubsub setup than in the blog post. One entity creates and manages, while the datachannel is responsible for subbing and unsubbing.

Sorry if I was unclear. I didn't mean to change the responsibility concerns. Currently, `websocket.go` exposes `Subscribe` and `Unsubscribe` which is good. I didn't mean to remove that--although we could move it to some other struct like `PubSub` that only deals with channels and the sub map if we want to keep the structs separate (and possibly reuse PubSub logic somewhere else).

> Also I absolutely think the client should be the one setting the buffer size since it's the client that knows what size buffer it should have based on its own use case.

Yeah I'm okay with this too. We could do something like this:

```
func (ps *Pubsub) Subscribe(topic string, bufferSize int) <-chan string {
  ps.mu.Lock()
  defer ps.mu.Unlock()

  ch := make(chan string, bufferSize)
  ps.subs[topic] = append(ps.subs[topic], ch)
  return ch
}
```

But that would require to also do the other refactor which would be having access to the channel type in `websocket.go` instead of calling `IChannel.Receive()`.

> I might be wrong but because we don't technically close any of the channels, websocket would never block on this, the message would just be put into a channel and never processed and eventually would be garbage collected.

In theory, the call to `Receive()` can block if the underlying channel buffer is full. Looks like it has a capacity of 25 right now, at least in the CC.

https://github.com/bastionzero/zli/blob/450aec470e2b0f2d25556cfaf892cfc3615b1494/kube-go-assets/bctl/agent/controlchannel/controlchannel.go#L64

This buffer will be full if `control.process(agentMessage)` (or `dataChannel.process()` for that matter) is taking too long to return, OR there is an influx of CC messages on the websocket _after_ `CloseWebsocketMessage` was processed by the CC. The processing of `CloseWebsocketMessage` causes the goroutine that is listening on `inputChan` to stop listening. If there are > 25 messages received after the goroutine that listens on `inputChan` closes, then `channel.Receive(agentMessage)` blocks forever meaning this goroutine never returns:

https://github.com/bastionzero/zli/blob/450aec470e2b0f2d25556cfaf892cfc3615b1494/kube-go-assets/bzerolib/channels/websocket/websocket.go#L93-L104

and as a side-effect, this one doesn't either

https://github.com/bastionzero/zli/blob/450aec470e2b0f2d25556cfaf892cfc3615b1494/kube-go-assets/bctl/agent/controlchannel/controlchannel.go#L202-L205

That's why I wanted to have a `select` statement so the `websocket` can stop waiting to send on `Receive()`/`inputCh` if the websocket tomb itself has been told to die.

2021-11-19 21:20 UTC, ymarcus93 commented on kube-go-assets/bctl/daemon/datachannel/datachannel.go
> +				dc.logger.Error(err)
Also, isn't this goroutine untracked by tomb?

2021-11-19 21:27 UTC, ymarcus93 commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +						channel.Receive(agentMessage)
But I guess actually for the latter case, the influx of messages won't be processed as this goroutine

https://github.com/bastionzero/zli/blob/450aec470e2b0f2d25556cfaf892cfc3615b1494/kube-go-assets/bzerolib/channels/websocket/websocket.go#L93-L104

won't call `receive()` if the tomb is dying. So maybe we're actually okay.

2021-11-22 19:40 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +			// case <-parentTmb.Dying():
This should be uncommented?

2021-11-22 19:40 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +	// TODO: We need to drop this session id auth header req and move to a token based system
Not sure I understand this comment?

2021-11-22 19:41 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +func (c *ControlChannel) process(agentMessage am.AgentMessage) error {
Can we add a comment here giving some context to this function? What's its purpose what's it doing?

Only asking since this is a decently important function and I think that'll clarify confusion later down the line

2021-11-22 20:00 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/plugin/kube/actions/exec/exec.go
> +	// TODO: Check request ID matches from startexec
We have helper functions for this, and I believe we are already doing this on line 103?

2021-11-22 20:11 UTC, sidpremkumar commented
lgtm, just need to do a in depth test tomorrow

2021-11-23 14:46 UTC, sidpremkumar commented
Logs + exec are both not working: 
![2021-11-23 at 9 45 AM](https://user-images.githubusercontent.com/28202162/143045746-c023c4f7-da07-41dd-8c06-be31ab9f0db2.png)

2021-11-23 15:03 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +			// case <-parentTmb.Dying():
controlchannel never receives a `parentTmb` because we don't currently have any logic in the agent code that would require that.  This is here mostly as a place holder, I can remove it if it bothers you

2021-11-23 15:05 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +			// case <-parentTmb.Dying():
Yeah lets remove it if we are not using it, Or lets leave a comment here explaining why it might be useful? Just thinking it might give the next person who takes a look more context.

2021-11-23 15:12 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +func (c *ControlChannel) process(agentMessage am.AgentMessage) error {
change name `process` -> `processInput`, can you specify exactly what is unclear/what kind of context you needed to figure out that we can put in there?

2021-11-23 15:13 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/exec/exec.go
> +	// TODO: Check request ID matches from startexec
this was a leftover old comment, deleted.

2021-11-23 15:16 UTC, sidpremkumar commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +func (c *ControlChannel) process(agentMessage am.AgentMessage) error {
If you don't think its necessary feel free to ignore this comment !

2021-11-23 17:52 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/datachannel/datachannel.go
> +				dc.logger.Error(err)
oh good catch

2021-11-23 17:53 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +func (c *ControlChannel) process(agentMessage am.AgentMessage) error {
42cfdae

2021-11-23 17:53 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +	// TODO: We need to drop this session id auth header req and move to a token based system
42cfdae

2021-11-23 17:53 UTC, lgmugnier commented on kube-go-assets/bctl/agent/controlchannel/controlchannel.go
> +			// case <-parentTmb.Dying():
42cfdae

2021-11-23 17:53 UTC, lgmugnier commented on kube-go-assets/bctl/daemon/datachannel/datachannel.go
> +				dc.logger.Error(err)
42cfdae

2021-11-23 17:54 UTC, lgmugnier commented on kube-go-assets/bctl/agent/plugin/kube/actions/exec/exec.go
> +	// TODO: Check request ID matches from startexec
42cfdae

2021-11-23 18:46 UTC, lgmugnier commented
> Logs + exec are both not working: ![2021-11-23 at 9 45 AM](https://user-images.githubusercontent.com/28202162/143045746-c023c4f7-da07-41dd-8c06-be31ab9f0db2.png)

exec seems to be working, looks like stream is having difficulties...debugging

2021-11-24 16:59 UTC, sidpremkumar commented
Also make sure to update the `VERSION` file for the agent to be 3.x.x. This should be a major version bump. (not sure if you did I couldn't find it but GitHub is hard to scroll with so many files 😓 )

2021-11-24 17:13 UTC, sidpremkumar approved these changes
Tested with Lens + k9s and was not able to break anything Nice! 🚢 Tested groups as well. 

Just make sure to take care of this https://github.com/bastionzero/zli/pull/234#issuecomment-978060548

2021-12-01 20:45 UTC, lgmugnier commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +						channel.Receive(agentMessage)
So I think what you're saying is that there is a problem if the datachannel's channels are full, we'll lose the messages if the websocket keeps sending stuff anyways.  I don't disagree and this is a known problem, but I don't understand the solution you're proposing.

2021-12-02 14:22 UTC, ymarcus93 commented on kube-go-assets/bzerolib/channels/websocket/websocket.go
> +						channel.Receive(agentMessage)
yeah actually i think it's fine. its just normal blocking/throttling until old messages get processed.

2021-12-02 14:25 UTC, ymarcus93 approved these changes

2021-12-08 17:35 UTC, merged