WIP Db Support
bastionzero/zli pull request #270
Opened 2021-12-14 14:33 UTC by sidpremkumar

## Description of the change

Description here (why is it needed, what does it do)....

## Relevant release note information

Release Notes:

## Related JIRA tickets

Relates to JIRA: CWC-XXX

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

2022-01-12 20:55 UTC, sidpremkumar commented on src/cli-driver.ts
> +        'db-connect',
remove these

2022-02-06 18:43 UTC, tflpd requested changes
Some comments are about the same file, made them everywhere just to make sure I didn't miss anything as `v1` will be very soon deleted and this would delete half of the things you added, it would be pretty catastrophic

2022-02-06 18:43 UTC, tflpd commented on src/services/common.types.ts
> +export interface TargetSummary extends TargetBase
this is an http type since it reflects the type the backend API serves, should be in common/http

2022-02-06 18:43 UTC, tflpd commented on src/services/db-target/db-target.service.ts
> +export class DbTargetService extends HttpService
http service, should be in http services

2022-02-06 18:43 UTC, tflpd commented on src/services/db-target/db-target.types.ts
> +export interface DbTargetSummary extends TargetBase {
common http

2022-02-06 18:43 UTC, tflpd commented on src/services/list-targets/list-targets.service.ts
> +    const bzeroAgentTargets = bzeroAgents.map<TargetSummary>((bzeroAgent) => {
Isnt this fetching and mapping being done already in the fetching middleware? If I am not mistaken it is not needed here as well.. Or actually the opposite, we have agreed with @lipmas that we will move away from pre-fetching things that we may not need so let's at least not add more fetching in that middleware, remove any VT fetching from there and leave it to be done here or wherever else needed

2022-02-06 18:43 UTC, tflpd commented on src/services/v1/policy-query/policy-query.messages.ts
> +
This file will be soon deleted don't add here, add to common/http

2022-02-06 18:43 UTC, tflpd commented on src/services/v1/policy-query/policy-query.service.ts
> +        super(configService, 'api/v2/policy-query/', logger); // TODO: This needs to change once thanos merges in his pr
Which PR?

2022-02-06 18:43 UTC, tflpd commented on src/services/v1/policy-query/policy-query.service.ts
> +        super(configService, 'api/v2/policy-query/', logger); // TODO: This needs to change once thanos merges in his pr
In any case this is wrong, if you want to use something from the v2 please use the http-services folder

2022-02-06 18:43 UTC, tflpd commented on src/services/v1/policy-query/policy-query.service.ts
> +
Don't add things here, this will be deleted. Also please use a more descriptive name for the method

2022-02-06 18:43 UTC, tflpd commented on src/services/web-target/web-target.service.ts
> +}
http-services

2022-02-06 18:43 UTC, tflpd commented on src/services/web-target/web-target.types.ts
> +}
common/http

2022-02-06 18:43 UTC, tflpd commented on src/utils/daemon-utils.ts
> +        await waitUntilUsedOnHost(localPort, localHost, 100, 1000 * 5).then(function() {
please make these const values on top of the file

2022-02-07 14:11 UTC, sidpremkumar commented on src/cli-driver.ts
> +                    // Add handlers for each type of target
https://github.com/bastionzero/zli/pull/270/commits/78d93a0305875ebfb89849b24ced997dfcc2f3fc

2022-02-07 14:12 UTC, sidpremkumar commented on src/cli-driver.ts
> +                'Disconnect a Zli Daemon',
yeah so now we just have multiple types of daemons. I've updated it to be more descriptive. https://github.com/bastionzero/zli/pull/270/commits/e562ddeec26b9419a4a2d0c1ee63ec767e182825

2022-02-07 14:14 UTC, sidpremkumar commented on src/cli-driver.ts
> +                        this.logger.error(`Unable to find target with given targetString: ${targetString}`);
https://github.com/bastionzero/zli/pull/270/commits/a90b28de9f211c099fb2276c7f06d6cc0a532f00

2022-02-07 14:26 UTC, sidpremkumar commented on src/handlers/connect/db-connect.handler.ts
> +    const response = await policyService.Proxy(dbTarget.id, dbTarget.remoteHost, dbTarget.remotePort, TargetType.Db);
https://github.com/bastionzero/zli/pull/270/commits/3f3eaf3596a2f4e4f00706bea93c5222715ccad7

2022-02-07 14:26 UTC, sidpremkumar commented on src/handlers/connect/db-connect.handler.ts
> +import { PolicyQueryService } from '../../services/v1/policy-query/policy-query.service';
https://github.com/bastionzero/zli/pull/270/commits/3f3eaf3596a2f4e4f00706bea93c5222715ccad7

2022-02-07 14:28 UTC, sidpremkumar commented on src/services/v1/policy-query/policy-query.service.ts
> +        super(configService, 'api/v2/policy-query/', logger); // TODO: This needs to change once thanos merges in his pr
no idea, i've reverted tho and switched to use the http service for proxy.

2022-02-07 14:28 UTC, sidpremkumar commented on src/services/v1/policy-query/policy-query.service.ts
> +
https://github.com/bastionzero/zli/commit/3f3eaf3596a2f4e4f00706bea93c5222715ccad7

2022-02-07 14:32 UTC, sidpremkumar commented on src/handlers/status/status.handler.ts
> +            logger.error('The Web Daemon has quit unexpectedly.');
https://github.com/bastionzero/zli/pull/270/commits/9ba6e7e54006a900c1bc0008f7710ac545058a2e

2022-02-07 14:34 UTC, sidpremkumar commented on src/services/web-target/web-target.service.ts
> +}
https://github.com/bastionzero/zli/pull/270/commits/c5112211f234e72132ed2a49ddfcc453359d6609

2022-02-07 14:35 UTC, sidpremkumar commented on src/services/db-target/db-target.service.ts
> +export class DbTargetService extends HttpService
https://github.com/bastionzero/zli/pull/270/commits/c5112211f234e72132ed2a49ddfcc453359d6609

2022-02-07 14:39 UTC, sidpremkumar commented on src/services/common.types.ts
> +export interface TargetSummary extends TargetBase
https://github.com/bastionzero/zli/pull/270/commits/ab2719eb445b90447bc1e76d5dfab39ac58bd68f

2022-02-07 14:41 UTC, sidpremkumar commented on src/services/bzero-agent/bzero-agent.service.ts
> +}
https://github.com/bastionzero/zli/pull/270/commits/c5112211f234e72132ed2a49ddfcc453359d6609

2022-02-07 14:42 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +            logger.error(`Failed to fetch db targets: ${e}`);
https://github.com/bastionzero/zli/pull/270/commits/19ea91e3b76d31b256d9b4ed5870c72b02227cca

2022-02-07 14:43 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +import { DbTargetService } from '../services/db-target/db-target.service';
https://github.com/bastionzero/zli/commit/c5112211f234e72132ed2a49ddfcc453359d6609

2022-02-07 14:45 UTC, sidpremkumar commented on src/handlers/status/status.handler.ts
> +import { StatusResponse } from '../../services/v1/kube/kube.types';
https://github.com/bastionzero/zli/pull/270/commits/c2cf9f67070866fc8f75922224984a7b50f6d976

I've moved to just status Handler. This is not a http request really, its just what we use to communicate to the daemon via localhost. So I don't think it belongs to common/http

2022-02-07 14:47 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +import { WebTargetService } from '../services/web-target/web-target.service';
https://github.com/bastionzero/zli/commit/c5112211f234e72132ed2a49ddfcc453359d6609

2022-02-07 14:50 UTC, sidpremkumar commented on src/utils/daemon-utils.ts
> +        await waitUntilUsedOnHost(localPort, localHost, 100, 1000 * 5).then(function() {
https://github.com/bastionzero/zli/pull/270/commits/168f928be3e7f340b0f4f23174e2668ac6b568d0

2022-02-07 15:17 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +import { WebTargetService } from '../services/web-target/web-target.service';
https://github.com/bastionzero/zli/pull/270/commits/3023213cf18269c89f4ddcba5770d4d94f02fd0e

my b, was in the middle of confirming w chad if I should (or he should) make this change. Updated to put in common now.

2022-02-07 15:17 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +import { WebTargetSummary } from '../services/web-target/web-target.types';
https://github.com/bastionzero/zli/pull/270/commits/3023213cf18269c89f4ddcba5770d4d94f02fd0e

2022-02-07 15:17 UTC, sidpremkumar commented on src/cli-driver.ts
> +import { DbTargetSummary } from './services/db-target/db-target.types';
https://github.com/bastionzero/zli/pull/270/commits/3023213cf18269c89f4ddcba5770d4d94f02fd0e

2022-02-07 15:17 UTC, sidpremkumar commented on src/handlers/connect/db-connect.handler.ts
> +import { DbTargetSummary } from '../../services/db-target/db-target.types';
https://github.com/bastionzero/zli/pull/270/commits/3023213cf18269c89f4ddcba5770d4d94f02fd0e

2022-02-07 15:19 UTC, tflpd commented on src/services/common.types.ts
> +export interface TargetSummary extends TargetBase
Same comment as Slack here for the file name please

2022-02-07 15:21 UTC, sidpremkumar commented on src/services/db-target/db-target.types.ts
> +export interface DbTargetSummary extends TargetBase {
forgot the commit, but this has been done

2022-02-07 15:21 UTC, sidpremkumar commented on src/services/bzero-agent/bzero-agent.types.ts
> +}
https://github.com/bastionzero/zli/pull/270/commits/2f366dd926cb8d4bc26fce7494c8b6a3ffec1a45

2022-02-07 15:22 UTC, sidpremkumar commented on src/services/web-target/web-target.types.ts
> +}
Forgot the commit, but this has been done

2022-02-07 15:25 UTC, sidpremkumar commented on src/services/common.types.ts
> +export interface TargetSummary extends TargetBase
https://github.com/bastionzero/zli/pull/270/commits/651ea4ce13bebaef180bbee8bd03f1a00f3eb688

2022-02-07 15:27 UTC, sidpremkumar commented on src/handlers/middleware.handler.ts
> +import { BzeroAgentSummary } from '../../src/services/bzero-agent/bzero-agent.types';
Forgot the commit , but here it is in webshell-common-ts: https://github.com/bastionzero/webshell-common-ts/pull/52/commits/8650448f2f673b03f0c4573db4a6f08895a70952

2022-02-07 16:20 UTC, sidpremkumar commented on src/services/list-targets/list-targets.service.ts
> +    const bzeroAgentTargets = bzeroAgents.map<TargetSummary>((bzeroAgent) => {
https://github.com/bastionzero/zli/pull/270/commits/11cf268a119fbcf34fee8538d4a85425b63f6e68

2022-02-07 16:46 UTC, sidpremkumar commented on src/handlers/connect/web-connect.handler.ts
> +        `-authHeader="${configService.getAuthHeader()}"`,
https://github.com/bastionzero/zli/pull/270/commits/636a9d2104dc6e5aeb05159571db350e556d2fef

2022-02-07 18:17 UTC, tflpd commented on src/handlers/connect/web-connect.handler.ts
> +        `-authHeader="${configService.getAuthHeader()}"`,
Nice! Thanks a lot!
Quick question, I see we moved from `kubeConfig['localPid']` to `kubeConfig.localPid`. Is it the same, I assume we tested that?

2022-02-07 18:20 UTC, sidpremkumar commented on src/handlers/connect/web-connect.handler.ts
> +        `-authHeader="${configService.getAuthHeader()}"`,
yeah since its an interface I figured it doesn't make sense to index like a dict, so that way we can get type inference and its easier to trace down. 

I did test with db (currently testing w web + kube) and it was working. Not expecting any issues on that change at least.

2022-02-07 18:28 UTC, tflpd commented on src/handlers/connect/web-connect.handler.ts
> +        `-authHeader="${configService.getAuthHeader()}"`,
Perf

2022-02-10 21:17 UTC, sidpremkumar commented
> Reference manual has to be updated for new flags and commands: https://github.com/bastionzero/docs/blob/master/zli/zli-reference-manual.md

Good point! updated here: https://github.com/bastionzero/zli/pull/270#issuecomment-1032920393

2022-02-11 22:51 UTC, lipmas approved these changes

2022-02-12 00:07 UTC, merged