Solve panics
bastionzero/zli pull request #294
Opened 2022-01-25 22:35 UTC by lgmugnier

## Description of the change

Make it so we don't need panics anymore and we can elegantly bubble up these errors to the user.

## Relevant release note information

Release Notes:

## Related JIRA tickets

Relates to JIRA: CWC-XXX

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

2022-01-26 11:49 UTC, sidpremkumar requested changes

2022-01-26 11:49 UTC, sidpremkumar commented on package.json
> +  "version": "5.4.1",
revert this, since we are merging into the feature branch no need to increment version. We can increment the version when we merge `feat/db-support` -> `master`

2022-01-26 11:49 UTC, sidpremkumar commented on src/handlers/connect/web-connect.handler.ts
> +            webConfig['localHost'] = 'localhost';
this should not be set to `'localhost'` rather it should be set to `localHost` the variable found on line 64

2022-01-26 11:49 UTC, sidpremkumar commented on src/utils/daemon-utils.ts
> +export async function handleServerStart(logPath: string, localPort: any) {
Couple of things: 
* `localPort` I believe should be an int so it can read `localPort: number` 
* we need to pass `localHost` as well here since for web and db targets we can have custom host. So instead of hardcoding the string `'localhost'` pass the host from the calling function.

2022-01-26 14:24 UTC, lgmugnier commented on package.json
> +  "version": "5.4.1",
2974b54

2022-01-26 14:25 UTC, lgmugnier commented on src/handlers/connect/web-connect.handler.ts
> +            webConfig['localHost'] = 'localhost';
2974b54

2022-01-26 14:25 UTC, lgmugnier commented on src/utils/daemon-utils.ts
> +export async function handleServerStart(logPath: string, localPort: any) {
2974b54

2022-01-27 20:40 UTC, sidpremkumar approved these changes
minor nits but this is ready to merge overall 🥳

2022-01-27 20:40 UTC, sidpremkumar commented on src/handlers/connect/db-connect.handler.ts
> +            logger.info(`Started db daemon at ${dbConfig['localHost']}:${localPort} for ${targetName}`);
can you change this to either use `dbConfig` for both host + port or `localHost` and `localPort` (the vars)

2022-01-27 20:40 UTC, sidpremkumar commented on src/utils/daemon-utils.ts
> +                            reject(`failed daemon startup\nLast log entry: ${lastLog.message}`);
Since this will be printed to the user, lets capitalize the first letters of all these reject statements?

2022-01-27 22:05 UTC, merged