Added Google Analytics for ZLI
bastionzero/zli pull request #304
Opened 2022-02-08 16:53 UTC by SaiprathapReddy7

## Description of the change

Created Google Analytics account for ZLI to track the users, events and etc.. 

## Relevant release note information

Release Notes: Added Google Analytics for ZLI

## Related JIRA tickets

Relates to JIRA: CWC-1632

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

2022-03-23 19:05 UTC, tflpd requested changes

2022-03-23 19:05 UTC, tflpd commented on src/services/config/config.service.ts
> +        return (await this.tokenHttpService.getGAToken()).token;
Maybe
```suggestion
        return (await this.tokenHttpService.getGAToken())?.token;
```
would be more safe

2022-03-23 19:05 UTC, tflpd commented on src/services/logger/logger.service.ts
> +        // Since the GA service is dependent on the logger, this will be set in the GA middleware in cil-driver
minor typo - 'cli-driver'*

2022-03-23 19:05 UTC, tflpd commented on src/services/v1/token/token.service.ts
>  import { ConfigService } from '../../config/config.service';
No changes should be made in this file and no other component should use it as this is deprecated and will be deleted soon

2022-03-23 19:05 UTC, tflpd commented on src/services/v1/token/token.messages.ts
> +export interface GATokenResponse
No changes should be made in this file and no other component should use it as this is deprecated and will be deleted soon

2022-03-23 19:05 UTC, tflpd commented on src/services/Tracking/Tracking.service.ts
> +export class GAService
Please name the class the same as the file - or the file the same as the class; for filenames we use lower case letters

2022-03-24 05:10 UTC, SaiprathapReddy7 commented on src/cli-driver.ts
> +
Removed extra space

2022-03-24 05:17 UTC, SaiprathapReddy7 commented on src/services/logger/logger.service.ts
> +        // Since the GA service is dependent on the logger, this will be set in the GA middleware in cil-driver
Updated typo error

2022-03-24 05:25 UTC, SaiprathapReddy7 commented on src/handlers/middleware.handler.ts
> + * Helper function to get our our GA tracking middleware and track our cli command
updated typo in the comment

2022-03-24 13:35 UTC, sidpremkumar commented on src/services/Tracking/Tracking.service.ts
> +    private visitor: any;
We only expect one type: https://github.com/peaksandpies/universal-analytics

But I was unsure of how to extract the type from that module
<img width="983" alt="2022-03-24 at 9 34 AM" src="https://user-images.githubusercontent.com/28202162/159927726-6e733731-46a2-4004-8d08-ff28075a5b60.png">

Tried a couple of different things but no luck :/

2022-03-24 13:35 UTC, sidpremkumar commented on src/services/Tracking/Tracking.service.ts
> +                    this.logger.error(`Error sending GA event zli-command: ${err}`);
+1 moved to debug

2022-03-24 13:36 UTC, sidpremkumar commented on src/services/Tracking/Tracking.service.ts
> +        await zliCommandCall;
Tried that originally but it was not sending events on calls to `cleanExit`. Happy to hop on a gmeet and try debugging together, but that was the code I had originally and was running into issues. 

I believe that the function call `this.visitor.event` is awaited, but not the callback possibly? I'm not sure tbh.

2022-03-24 13:37 UTC, sidpremkumar commented on src/services/Tracking/Tracking.service.ts
> +            await this.visitor.event('zli-error', 'lt', (err: any) => {
Yup thanks, this should have been `baseCommand`

2022-03-24 13:42 UTC, sidpremkumar commented on src/services/Tracking/Tracking.service.ts
> +export class GAService
https://github.com/bastionzero/zli/pull/304/commits/d018c950cff0dacd67575e85a499fd5c710d8650

2022-03-24 13:42 UTC, sidpremkumar commented on src/services/v1/token/token.messages.ts
> +export interface GATokenResponse
https://github.com/bastionzero/zli/pull/304/commits/d018c950cff0dacd67575e85a499fd5c710d8650

2022-03-24 13:42 UTC, sidpremkumar commented on src/services/v1/token/token.service.ts
>  import { ConfigService } from '../../config/config.service';
https://github.com/bastionzero/zli/pull/304/commits/d018c950cff0dacd67575e85a499fd5c710d8650

2022-03-24 13:42 UTC, sidpremkumar commented on src/services/config/config.service.ts
> +        return (await this.tokenHttpService.getGAToken()).token;
https://github.com/bastionzero/zli/pull/304/commits/d018c950cff0dacd67575e85a499fd5c710d8650

2022-03-24 13:43 UTC, sidpremkumar commented on src/http-services/token/token.http-services.ts
> +        return this.Get('GA-token', {});
https://github.com/bastionzero/zli/pull/304/commits/d018c950cff0dacd67575e85a499fd5c710d8650

2022-04-01 13:54 UTC, tflpd commented on src/services/Tracking/Tracking.service.ts
> +    private visitor: any;
Hm, I guess they do not really have support for TS, alright!
Feel free to resolve

2022-04-01 14:27 UTC, tflpd commented on src/services/Tracking/Tracking.service.ts
> +export class GAService
I still see both the folder and the filename capitalized

2022-04-01 14:29 UTC, tflpd commented on src/services/Tracking/Tracking.service.ts
> +export class GAService
My bad, it is just the folder actually

2022-04-01 15:12 UTC, tflpd submitted a review, later dismissed

2022-04-05 11:21 UTC, sidpremkumar approved these changes

2022-04-05 12:36 UTC, merged