Made commands case insensitive [CWC-1460]
bastionzero/zli pull request #330
Opened 2022-03-04 21:54 UTC by danimelchor

## Description of the change
Converted camelCase commands to lowercase commands. Process args are split and the command is lower cased to allow for case-insensitive commands.

Example:
Previously, `zli targetuser [...]` would fail. Now, all variations of `targetuser` are valid (`targetUser`,`TargetUser`,`TARGETUSER`...)

## Relevant release note information

Release Notes:

## Related JIRA tickets

Relates to JIRA: CWC-1460

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [X] No

If yes, please explain: N/A

2022-03-04 23:17 UTC, sidpremkumar commented
Looking good 🥳 , one thing you'll need to do is update the kube system tests here: https://github.com/bastionzero/zli/blob/fix/condence-agent-public-key/src/system-tests/tests/suites/kube.ts#L152-L169

Since now you'll be using a different command `targetUser` -> `targetuser`

2022-03-05 02:22 UTC, tflpd requested changes

2022-03-05 02:22 UTC, tflpd commented on src/cli-driver.ts
> +    }
Let's put this in utils

2022-03-05 02:22 UTC, tflpd commented on src/system-tests/tests/utils/zli-utils.ts
> +
Let's make this a `function` to keep the existing pattern

2022-03-05 02:38 UTC, danimelchor commented on src/system-tests/tests/utils/zli-utils.ts
> +
[b3571c6](https://github.com/bastionzero/zli/pull/330/commits/b3571c6383b496b52aebe7057981b64c4272ba08)

2022-03-05 02:38 UTC, danimelchor commented on src/cli-driver.ts
> +    }
[b3571c6](https://github.com/bastionzero/zli/pull/330/commits/b3571c6383b496b52aebe7057981b64c4272ba08)

2022-03-06 22:38 UTC, sidpremkumar commented
> Looking good 🥳 , one thing you'll need to do is update the kube system tests here: https://github.com/bastionzero/zli/blob/fix/condence-agent-public-key/src/system-tests/tests/suites/kube.ts#L152-L169
> 
> Since now you'll be using a different command `targetUser` -> `targetuser`

Hey @danimelchor @tflpd pointed out to me that this PR should have ensured that this change should have been needed (even though we still should update sys tests to reflect the lowercase name).

But yeah this change should have been unneeded for sys tests to pass. My b!

2022-03-06 22:52 UTC, danimelchor commented
> > Looking good 🥳 , one thing you'll need to do is update the kube system tests here: https://github.com/bastionzero/zli/blob/fix/condence-agent-public-key/src/system-tests/tests/suites/kube.ts#L152-L169
> > Since now you'll be using a different command `targetUser` -> `targetuser`
> 
> Hey @danimelchor @tflpd pointed out to me that this PR should have ensured that this change should have been needed (even though we still should update sys tests to reflect the lowercase name).
> 
> But yeah this change should have been unneeded for sys tests to pass. My b!

Yep! I realized as well. Just had to add transformation to lower case in the tests instead of changing the commands executed. However, I think it's good to have the tests use the same command that is specified in the documentation.

2022-03-17 22:22 UTC, closed without merging