PWDB 1/3 -- New flows for generating certs and connecting
bastionzero/zli pull request #625
Opened 2023-02-09 22:27 UTC by johncmerfeld

## Description of the change

  - Add the `zli generate certificate` command in all its glory
  - Update the `policy` command to reflect the changes to proxy policies
  - Move some files around

## Testing

Describe how to test this PR....

**backend branch:** 
**bzero branch:** 
**charts branch:** 

#### Ready to run system tests?

- [ ] Yes

## Relevant release note information

Release Notes: New flows for generating certs and connecting to SplitCert targets

## Related JIRA tickets

Relates to JIRA: CWC-2132, CWC-2129

## Relevant HotFix if applicable

Relevant HotFix PR Number:

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [x] No

If yes, please explain:

2023-02-14 16:09 UTC, tflpd requested changes

2023-02-14 16:09 UTC, tflpd commented on src/http-services/db-target/db-target.http-service.ts
> +    }
I would probably just add these as optional parameters to the `List` method to keep things concise but this is personal preference feel free to ignore

2023-02-14 19:13 UTC, johncmerfeld commented on src/handlers/connect/db-connect.handler.ts
> +import { bool } from 'aws-sdk/clients/signer';
I believe Lucie mistakenly put `bool` instead of `boolean` as a variable type, and this import was created. Fixing

2023-02-14 19:25 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +    fs.writeFileSync(path.join(outputDir, paths.caCert), certResponse.caCert, options);
I guess I don't see why blocking is considered a problem in this case. We don't want to return to the user until the files have all been written, so we should wait for them to finish writing, no?

2023-02-14 19:31 UTC, tflpd commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +    fs.writeFileSync(path.join(outputDir, paths.caCert), certResponse.caCert, options);
Correct. Awaiting an async method achieves exactly that without blocking the main thread

2023-02-14 19:32 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +            agentVersion = new SemVer(target.agentVersion);
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +        // FIXME: shouldn't accept this in production
Yep, in fact this can be even simpler; not sure why I did it this way 
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +            cleanExit(1, logger);
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +        cleanExit(1, logger);
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/handlers/connect/db-connect.handler.ts
> +    isPasswordless: bool,
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/handlers/connect/db-connect.handler.ts
> +import { bool } from 'aws-sdk/clients/signer';
8d5eeabe

2023-02-14 19:33 UTC, johncmerfeld commented on src/cli-driver.ts
> +                            async (argv) => certificateHandler(argv, this.configService, this.logger)
8d5eeabe

2023-02-14 19:45 UTC, johncmerfeld commented on src/handlers/generate/certificate/generate-certificate.handler.ts
> +    fs.writeFileSync(path.join(outputDir, paths.caCert), certResponse.caCert, options);
Fair enough. If that's our convention I'm good with it. 80ecbfae

2023-02-14 20:29 UTC, johncmerfeld commented on src/handlers/connect/db-connect.handler.ts
> +    let action = 'dial'
Given that the action name is only used in a single function call, I'm gonna keep it the way it is for now for simplicity's sake.

2023-02-14 21:39 UTC, tflpd approved these changes

2023-02-17 16:26 UTC, ymarcus93 reviewed
Very cool!

2023-02-17 16:33 UTC, johncmerfeld commented on src/handlers/connect/db-connect.handler.ts
> +
I'll let @lgmugnier  answer but it's possible this was unintentional. Personally I'll admit to not having a full grasp on how to best use a `dbDaemonManagementService`

2023-02-17 17:36 UTC, lgmugnier commented on src/handlers/connect/db-connect.handler.ts
> +
> My only concern here is if handleServerStart fails, we no longer have track of the db daemon anymore in config for zli. Which means disconnect won't work (but close will).

So, there are two major errors that can happen in `handleServerStart`, one of which is that the daemon theoretically starts up and never responds and the other is that the daemon fails on start up and exits. Each require different error-handling behavior. The previous ordering led dead daemons to being kept track of for no reason (they're already dead). 

That being said, I'm still probably not correctly handling error case where the daemon starts up and isn't responding for whatever reason and we would want to kill it at that point. I would argue that if the daemon starts up and doesn't respond in a reasonable time, we should kill it and not keep track of it until the user types a `zli disconnect` or `zli close` to manage that.

2023-02-17 21:58 UTC, lgmugnier commented on src/handlers/connect/db-connect.handler.ts
> +
There are two main issues we can run into on startup: daemon exits with error, daemon time out on startup. For the former, the daemon is already dead, but we should be making sure that when the daemon takes too long to startup, we're making sure to kill in. Therefore, we don't need to track daemons in either fail case and can only begin tracking after they've successfully started up.

2023-02-17 21:58 UTC, lgmugnier commented on src/handlers/connect/db-connect.handler.ts
> +
fc846ed

2023-02-21 17:12 UTC, ymarcus93 approved these changes

2023-02-21 17:20 UTC, merged