The Config Issue
bastionzero/zli pull request #662
Opened 2023-04-11 17:17 UTC by lgmugnier

## Description of the change

Please see the referred ticket for a full explanation, but the short of it is that we need to put some of our credential values (`tokenset` and `mrtap`) into the windows registry.

## Testing

Describe how to test this PR....

**backend branch:** 
**bzero branch:** 
**charts branch:** 

#### Ready to run system tests?

- [ ] Yes

## Relevant release note information

Release Notes:

## Related JIRA tickets

Relates to JIRA: CWC-2516

## Relevant HotFix if applicable

Relevant HotFix PR Number:

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

Does this PR add a new/modifies the name/arguments of a `zli` command?

- [ ] Yes
- [ ] No

If yes, please provide the docs/zli-reference-manual branch reflecting the changes:

2023-04-11 19:50 UTC, johncmerfeld commented on src/services/logger/logger-config.service.ts
> +            configDir = path.join(process.env.LOCALAPPDATA, projectName)
Okay so even on windows we're still using conf for the logger configuration?

2023-04-11 19:53 UTC, johncmerfeld commented on src/services/config/config.service.ts
> +        }
IMO there's no reason to exclude aix, freebsd, openbsd, and sunos from ZLI support; they're all unix-based, so this can just be 
```suggestion
        } else {
            this.config = new UnixConfig(projectName, configName, configDir, isSystemTest, serviceUrl);
        }
```

2023-04-11 19:59 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +        })
I think future engineers would appreciate some context here as to what we're doing and why. Even if it's just a couple well-chosen links

2023-04-11 20:08 UTC, johncmerfeld commented on src/services/logger/logger-config.service.ts
> +            configDir = path.join(process.env.LOCALAPPDATA, projectName)
Oh, I see, we're even still using it for most config values. Understood

2023-04-11 20:15 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +        this.config = new Conf<ConfigSchema>({
Assuming we don't have to move literally everything to the registry, is there a way we can use less duplicated code between this `Conf` and the unix one? For example, we could treat this `ConfigSchema` as the base type and then extend it to include the extra Unix fields. Using that and some similar techniques, it seems like most of the next ~150 lines could be factored out. Maybe there are other reasons we don't want to do that, though?

2023-04-11 20:15 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            migrations: {
In fact I don't even think we need these migrations, since no one will be using a windows ZLI prior to this version

2023-04-11 20:24 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            // after it has been cleared. We can safely ignore it.
Not sure I understand this

2023-04-11 20:25 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +    }
Again, it's possible this is more trouble than it's worth, but I'm wondering whether we shouldn't just do this the old-fashioned inheritance way and have a parent class that implements all of these `config` getters/setters, and then a Windows child class that overrides only the methods it needs to. What do you think?

2023-04-11 20:28 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +                    resolve('');
Why is `''` the correct return here? Or rather, why does this function return a `Promise<string>` instead of a `Promise<string | null>`?

2023-04-11 20:29 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            // Ignore errors if the key can't be found which is normal
lol, why is this normal?

2023-04-11 20:30 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            }
This seems like a fatal error, no? I'm curious why we're essentially ignoring it

2023-04-12 00:11 UTC, lgmugnier commented on src/services/logger/logger-config.service.ts
> +            configDir = path.join(process.env.LOCALAPPDATA, projectName)
yes, exactly. I really wanted to just do the bare minimum for now. It's possible there is a future PR where everything moves to the windows registry but until I have proof that's what  we need to do, it'll stay with conf.

2023-04-12 00:33 UTC, lgmugnier commented on src/services/config/config.service.ts
> +        }
I don't disagree with this but I don't know if we do want to make this change because it shifts some os's into an "implicit support" category which we don't have any explicit testing for in our matrix. I think we should get a thumbs up from the team before making the change and then make sure it's consistent across all of these such if statements.

2023-04-12 01:28 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        })
I added some more context in 1f18238 but I'm not sure how much more to clarify without pasting wikipedia links about how the windows registry works unless you think a little blurb about how the windows registry works is helpful here? something like:
"The Windows Registry is key-value storage. It has "hives" which are the root keys and generally separate out further nesting into priveleged categories. Our key lives in the application ("Software") section in a special new subkey "BastionZero""

2023-04-12 01:29 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +            }
Please check 1f18238 to see if I handled the error correctly. Essentially, now I throw errors if we hit one and pass that up until I get to a function that can call `cleanExit`

2023-04-12 01:33 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +            // after it has been cleared. We can safely ignore it.
By virtue of how remove works, we often hit the error that the key we're looking for doesn't exist. I think it was a bit confusing before so I've added a new function to check if we're hitting that kind of error and not report if that's the case. I also consolidate this exact point into a comment in that function. Check it out to see if it's any clearer 1f18238

2023-04-12 01:38 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        this.config = new Conf<ConfigSchema>({
I wanted to consolidate your comments in this vein into one so I chose this comment. 

This is a great idea, I think I refrained from doing that because 1 I was poisoned by go but 2 because I did think that moving everything to the windows registry was a very real prospect. I'm happy to make this change now even if we do still need to move everything to the registry. And I'm happy to be doing so in a language that has good, traditional inheritance.

2023-04-12 15:19 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +        })
I actually think that would be super helpful, yeah!

2023-04-12 15:24 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            // after it has been cleared. We can safely ignore it.
I see. Yep, appreciate the additional info in the code and the function is a good idea!

2023-04-12 15:37 UTC, johncmerfeld commented on src/handlers/middleware.handler.ts
> +            throw e;
No need to try/catch/throw. If setOrgBZCertValidationInfo throws an error, it'll get thrown automatically here

2023-04-12 15:38 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +        return err.message.indexOf('The system was unable to find the specified registry key or value') != -1
```suggestion
        return err.message.includes('The system was unable to find the specified registry key or value');
```

2023-04-12 15:44 UTC, johncmerfeld commented on src/services/config/windows-config.service.ts
> +            }
Well-handled, I think! But added one more comment

2023-04-12 17:32 UTC, tflpd commented on src/services/config/config.service.ts
> +        }
For what is worth, I agree that we should only be using what we are testing. There should be a clear, Product-specified list of OSs we support and have our code support them and test for them in some way. It may be cumbersome to test for them in every PR so we could just test all of them in the CI, but still, that's the proper way of doing things

2023-04-13 11:14 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        })
b3429fd

2023-04-13 13:04 UTC, lgmugnier commented on src/handlers/middleware.handler.ts
> +            throw e;
wasn't sure about that so thank you for clarifying!

2023-04-13 14:14 UTC, lgmugnier commented on src/services/config/config.service.ts
> +        }
alright, conclusion from the meeting sides with @johncmerfeld. We can easily put all of our unix support into an "else" statement.

2023-04-13 14:18 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        return err.message.indexOf('The system was unable to find the specified registry key or value') != -1
2077e00

2023-04-13 14:18 UTC, lgmugnier commented on src/handlers/middleware.handler.ts
> +            throw e;
2077e00

2023-04-13 14:18 UTC, lgmugnier commented on src/services/config/config.service.ts
> +        }
2077e00

2023-04-13 14:56 UTC, tflpd requested changes

2023-04-14 13:20 UTC, lgmugnier commented on src/handlers/login/login.handler.ts
>      }
because `setTokenSet` can also throw an error

2023-04-14 13:36 UTC, lgmugnier commented on src/handlers/login/login.handler.ts
> +        logger.error(`failed to login: ${e}`);
checking with @asamborski about the error messages

2023-04-19 12:49 UTC, lgmugnier commented on src/cli-driver.ts
> +                }
67a122c

2023-04-19 12:50 UTC, lgmugnier commented on src/handlers/login/login.handler.ts
> +        logger.error(`failed to login: ${e}`);
checked and made changes in 67a122c

2023-04-19 13:35 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        // this.config.onDidChange('tokenSet', callback);
398548a

2023-04-19 15:59 UTC, tflpd commented on src/services/config/windows-config.service.ts
> +        // this.config.onDidChange('tokenSet', callback);
should `logoutOnTokenSetCleared` be added in the interface?

2023-04-19 16:38 UTC, lgmugnier commented on src/handlers/login/login.handler.ts
> +        logger.error(`failed to login: ${e}`);
76616a4 I've fixed it so that they start with a capital letter but I don't understand why error would need to end in a period. It doesn't seem like we have that convention overall and I disagree that we would want it particularly since errors are things that get bubbled up and it's hard to keep track of punctuation.

2023-04-19 16:44 UTC, lgmugnier commented on src/handlers/register/register.handler.ts
> +        logger.error(`failed to save tokens after oath refresh: ${e}`);
76616a4

2023-04-19 17:05 UTC, lgmugnier commented on src/handlers/login/login.handler.ts
> +        logger.error(`failed to login: ${e}`);
They do get concatenated if you have a `reject(blah)` and then a `catch (e) { logger.error('hit error: ${e}') }`. 

In this situation, there are very few periods in the login flow messages and I think having punctuation only at the end of error messages is awkward.

There is a clear lack of cohesion in the existing code base, we should just get a consensus decision and fix everything at once in a separate PR.

2023-04-19 18:11 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +        this.config = new Conf<ConfigSchema>({
e7f4ed7

2023-04-19 18:12 UTC, lgmugnier commented on src/services/config/windows-config.service.ts
> +                if (!err) {
4b7b154

2023-04-19 18:43 UTC, tflpd approved these changes

2023-04-19 19:02 UTC, johncmerfeld approved these changes
Love this!!

2023-04-19 19:19 UTC, merged