Refresh lock
bastionzero/zli pull request #680
Opened 2023-05-03 14:43 UTC by lgmugnier

## Description of the change

Put a lock around our refresh lock so that when multiple daemons are refreshing, they do not conflict and it doesn't accidentally wipe your creds.

## Testing

Describe how to test this PR....

**backend branch:** 
**bzero branch:** 
**charts branch:** 

#### Ready to run system tests?

- [x] Yes

## Relevant release note information

Release Notes: Make refresh safe

## Related JIRA tickets

Relates to JIRA: CWC-2563

## Relevant HotFix if applicable

Relevant HotFix PR Number:

## Have you considered the security impacts?

Does this PR have any security impact?

- [ ] Yes
- [ ] No

If yes, please explain:

Does this PR add a new/modifies the name/arguments of a `zli` command?

- [ ] Yes
- [ ] No

If yes, please provide the docs/zli-reference-manual branch reflecting the changes:

2023-05-03 16:15 UTC, tflpd requested changes
Should we add a lock around register handler as well?

2023-05-03 16:25 UTC, lgmugnier commented on src/services/oauth/oauth.service.ts
> +const retry = require('retry');
bad93f0

2023-05-03 16:38 UTC, lgmugnier commented
>Should we add a lock around register handler as well? 
When is `zli register` called? If it's only called during system tests then I think we're good.

2023-05-03 16:57 UTC, tflpd commented on src/services/oauth/oauth.service.ts
> +        }
Yup! SAs do not have refresh logic, when their idT expires (once every week atm), they need to log in again

2023-05-03 17:13 UTC, tflpd commented on src/services/oauth/oauth.service.ts
>                  }
If something like this works it would be preferred as Promises are the old way of doing async/await
```
        const release = await lockfile.lock(lockName, {
            realpath: false,
            stale: 5000, // 5 seconds
            retries: {
                retries: 20,
                minTimeout: 300, // The number of milliseconds before starting the first retry
                maxTimeout: 500, // The maximum number of milliseconds between two retries
                maxRetryTime: 5 * 5000 // The maximum time (in milliseconds) that the retried operation is allowed to run
            }
        })

        // Maybe another process refreshed while we were waiting, so we check again
        // in case we don't need to go through the refresh process
        if (await this.isAuthenticated()) {
            tokenSet = await this.configService.getTokenSet();
            await release();
            return tokenSet.id_token
        }

        this.logger.debug('Refreshing OAuth tokens');
        try {
            tokenSet = await this.refresh();
        } catch (e) {
            release();

            this.logger.debug(`Failed to refresh OAuth tokens. ${e.message}`);
            if (e instanceof errors.RPError || e instanceof errors.OPError) {
                throw new RefreshTokenError();
            } else {
                throw e;
            }
        }

        this.configService.setTokenSet(tokenSet);
        this.logger.debug('OAuth tokens refreshed');

        const userHttpService = new UserHttpService(this.configService, this.logger);
        await userHttpService.Register();

        // Update me section of the config in case this is a new login or any
        // user information has changed since last login
        const subjectHttpService = new SubjectHttpService(this.configService, this.logger);
        const me = await subjectHttpService.Me();
        this.configService.setMe(me);

        await release();
        return tokenSet.id_token;
```

2023-05-03 17:13 UTC, tflpd commented on src/services/oauth/oauth.service.ts
>                  }
Note that I have altogether removed the catch block you were using - up to you whether you want more granular control and add one per lock/release or add one that covers all

2023-05-04 15:34 UTC, lgmugnier commented on src/services/oauth/oauth.service.ts
>                  }
001c74a

2023-05-04 15:50 UTC, johncmerfeld approved these changes
Logged in around 7am. Didn't do anything else. Ran the script around 11am and it worked

2023-05-04 16:59 UTC, tflpd approved these changes
Nice, some comments need updating, LGTM other than that!

2023-05-04 17:00 UTC, tflpd commented on src/services/oauth/oauth.service.ts
>                  }
Oh, glad it works, I wasn't 100% it will!

2023-05-04 20:53 UTC, lipmas approved these changes
Tested using the python script on linux and its working.

2023-05-04 20:55 UTC, lipmas commented
@lgmugnier Added the `ci-run-google` label to the PR now which it doesnt run by default if you add other ci labels. But this is a required status check. But you will need to push one more commit in order to get it to run that CI.

2023-05-04 22:09 UTC, merged