Fix/close ssh tunnels on logout [CWC-628]
bastionzero/zli pull request #99
Opened 2021-04-27 20:36 UTC by tflpd

## Description of the change

This fixes the bug when there are multiple instances of the zli running and one of them logs out, the others would not pick up the change and close any open tunnels.

In order to test this:
- Open a terminal. Login to zli. Connect to a server from this terminal.
- Open a second terminal. Execute logout.
- Check both terminals. Both should be disconnected and logged out without any error messages. Make sure you look in the logs of both the zli and the webapp please, we have noticed some discrepancies and we want to make sure those do not show up anymore.
- Extra test : try logging in and connecting again to the server.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (code change with no functionality change)
- [ ] Enhancement (minor change below the level of a feature)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Remove feature (removes a feature we don't support anymore)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related JIRA tickets

Relates to JIRA: CWC-628

## Potential Security Impacts

## Checklists

### Development

- [ ] Does the code changed/added as part of this pull request have test coverage?
- [ ] Do all tests related to the changed code pass in development?
- [ ] Have you ensured that at least one other person has tested your code?
- [X] Have you tested the code?
- [ ] Have you attached any pictures (if relevant)?

2021-04-27 21:00 UTC, Nabeelperson commented on src/handlers/logout.handler.ts
> +    }
This should probably be made into a utility function as the logic is repeated in connect-handler as well.

2021-04-27 21:36 UTC, EthanHeilman commented
In the PR description describe not just how to replicate and test the problem but what the proposed solution in the PR is.

2021-04-28 12:50 UTC, sidpremkumar commented on src/handlers/logout.handler.ts
> +import _ from 'lodash';
Similar to what Sebby said in Nabeels PR, we should probably explicitly import what we need from `lodash`

2021-04-28 12:50 UTC, sidpremkumar commented on src/handlers/logout.handler.ts
> +    logger.debug('Closing any open cli connections');
Should this be a `logger.info`? Thinking the user might be confused if they log out of the zli and their connections close, they might not understand what closed them. 

Not sure though.

2021-04-28 13:04 UTC, tflpd commented
> In the PR description describe not just how to replicate and test the problem but what the proposed solution in the PR is.

@EthanHeilman added

2021-04-28 13:14 UTC, tflpd commented on src/handlers/logout.handler.ts
> +    }
The logic is indeed very similar, however the `cliSpace.length === 0` case is different here from the connect handler. I guess I can add something like a flag and apply the right logic every time - do we want that? I don’t really like this idea

2021-04-28 13:14 UTC, tflpd commented on src/handlers/logout.handler.ts
> +import _ from 'lodash';
@Nabeelperson what's your take in this?

2021-04-28 13:15 UTC, tflpd commented on src/handlers/logout.handler.ts
> +    logger.debug('Closing any open cli connections');
Hm, okay, I think I agree with you in this. Let's see what the others say and if they agree as well I will add it

2021-04-28 13:35 UTC, Nabeelperson commented on src/handlers/logout.handler.ts
> +    }
Well the logic here can return you `undefined` or the `cliSession` object, then the caller can choose how to handle the returned value.

2021-04-28 13:37 UTC, Nabeelperson commented on src/handlers/logout.handler.ts
> +import _ from 'lodash';
@sidpremkumar @tflpd we have this issue across the entire code base. When we decide to fix this we should do it in one shot across the entire code base and then make it part of the our code standards for thoum to not import lodash in its entirety.

2021-04-28 13:38 UTC, Nabeelperson commented on src/handlers/logout.handler.ts
> +    logger.debug('Closing any open cli connections');
Info is good, should probably say `Closing all other instances of zli` or something along those lines.

2021-04-28 13:39 UTC, tflpd commented on src/handlers/logout.handler.ts
> +    }
Yes but the if case in the connect handler should not have the `cleanExit` in line 24 which the logout needs, right?

2021-04-28 13:44 UTC, lipmas requested changes
It seems like this PR is only addressing closing existing connections opened with `zli connect` when the user logs out...but it wont have any effect on any existing open ssh tunnels. In order to close any existing ssh tunnels that are opened with the zli i think you would need to catch the logout event in the ssh-proxy handler https://github.com/bastionzero/zli/blob/master/src/handlers/ssh-proxy.handler.ts

2021-04-28 13:44 UTC, lipmas commented on src/handlers/connect.handler.ts
> -            await cleanExit(0, logger);
Why are we removing this logic? Now when a user exits a `zli connect` command normally (typing exit, logout, or ctrl+d) the connection would no longer be cleaned up automatically and will have to be closed through the web app or logging out of the zli.

Is this change in behavior what we want @Nabeelperson @tflpd ?

2021-04-28 14:00 UTC, Nabeelperson commented on src/handlers/connect.handler.ts
> -            await cleanExit(0, logger);
Good catch, that was an oversight when I made the changes to just get the logout flow working. @tflpd may you revert this change and see how to address the ssh tunnel logout cases?

2021-04-28 14:15 UTC, Nabeelperson commented on src/handlers/logout.handler.ts
> +    }
Your observation is correct. The function I am proposing returns a cli space, does not do anything about closing thoum, that is the responsiblity of the caller to that function.

2021-04-28 14:21 UTC, tflpd commented
Following up [CWC-628](https://commonwealthcrypto.atlassian.net/browse/CWC-628) comments this feature is not the requested solution, thus this PR is being closed

2021-04-28 14:21 UTC, closed without merging